spring.application.name=back


spring.datasource.url=jdbc:postgresql://localhost:5432/FilmBiblio
spring.datasource.username=cine
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html